### ISSUE TITLE
Horizontal view

### ISSUE THREAD

**Issue by mitjarogl** [VadimDez/ng2-pdf-viewer#378]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Bug report -> please search issues before submitting
- [x] Feature request
- [ ] Documentation issue or request
```

Is it possible to support horizontal scroll view. Thanks.

**Comment by VadimDez** [comment]
It should be possible by adding some CSS.
For example:
```css
pdf-viewer .ng2-pdf-viewer-container .pdfViewer {
  display: flex !important;
}
```
