### ISSUE TITLE
[7.0.1] width of pdf page exceed the maximum width and got trimmed from the right side

### ISSUE THREAD

**Issue by almothafar** [VadimDez/ng2-pdf-viewer#805]
##### Bug Report or Feature Request (mark with an `x`)
```
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Bug report -> please search issues before submitting
- [ ] Feature request
- [ ] Documentation issue or request
```
I have an issue with a pdf exceeding the width from style `max-width` which is mentioned in the docs, but seems that does not work, that issue happened with the latest changes (version 7.0.1).

![image](https://user-images.githubusercontent.com/13887564/122673829-ed586100-d1da-11eb-95a7-ad559c5c7998.png)

I was using it as simple as:

```
<pdf-viewer [original-size]="false" [render-text]="false" [src]="pdfUrl" style="display: block; max-width: 1200px; margin: 0 auto;"></pdf-viewer>
```
Which was working, and tried: 
```html
<pdf-viewer [original-size]="false" [zoom-scale]="'page-width'" [fit-to-page]="true"  [autoresize]="true" [render-text]="false" [src]="pdfUrl"
              style="display: block; max-width: 1200px; margin: 0 auto;"></pdf-viewer>
```

Nothing worked, but when I changed `.ng2-pdf-viewer-container` to be `position: relative` it is worked fine.

![image](https://user-images.githubusercontent.com/13887564/122673844-0c56f300-d1db-11eb-8424-765333397aba.png)

So the change that I can say is behind this issue is this: https://github.com/VadimDez/ng2-pdf-viewer/commit/8d4f8ad25107a98e920ab18e32b828c2e5597e54#diff-c0a5f3426a537629a18cbeb63abc55b7ce727f267c2e85acf84c88ddd96e4cb1R3

The problem solved only runtime, but if I do something like:
```scss
pdf-viewer {
  ::ng-deep {
    .ng2-pdf-viewer-container {
      position: relative;
    }
  }
}
  ```

I get only blank screen.

The workaround for this is to make the style inside `pdf-viewer` tag:

```scss
pdf-viewer {
  ::ng-deep {
    .ng2-pdf-viewer-container {
      max-width: 1200px;
    }
  }
}
  ```
